# Site settings
title: Chengyue Gong
description: I am a full-stack developer.
show_downloads: false
resume_url: https://github.com/chengyuegong/chengyuegong.github.io/raw/master/docs/Resume_Chengyue%20Gong.pdf
google_analytics: UA-136835729-1
theme: jekyll-theme-cayman

# Contact information
email: chengyueg@wustl.edu
github_username: chengyuegong
linkedin_link: https://www.linkedin.com/in/chengyue-gong-43233711a/
